### ISSUE TITLE
other simple way to change boot order

### ISSUE THREAD

**Issue by cherwey** [scawp/Steam-Deck.Force-SteamOS-On-Boot#1]
1.copy all esp: /efi/Microsoft/*.* file to /efi/WMicrosoft/  
2.del 2 file /efi/Microsoft/boot/bootmgfw.efi and bootmgr.efi   /*win shutdown neet this dir*/
3.use UEFI tools chang [Windows boot Manager] Path to /efi/WMicrosoft/boot/bootmgfw.efi
finish. steamos will boot first

**Comment by cherwey** [comment]
maybe can copy /efi/steam to /efi/asteam to change order

**Comment by scawp** [comment]
Thanks for the tip! Closing but keeping visible for others
